apiVersion: v1
kind: Service
metadata:
  name: book-service
spec:
  selector:
    app: book-deployment
  ports:
    - protocol: TCP
      port: 3000 # External port clients will use to access the service
      targetPort: 3000 # Port on the pods where traffic will be forwarded

