apiVersion: v1
kind: Service
metadata:
  name: crm-service
spec:
  selector:
    app: crm-deployment
  ports:
    - protocol: TCP
      port: 8080 # External port clients will use to access the service
      targetPort: 8080 # Port on the pods where traffic will be forwarded

