apiVersion: v1
kind: Service
metadata:
  name: mobile-app-bff-service
spec:
  selector:
    app: mobile-bff-deployment
  ports:
    - protocol: TCP
      port: 80 # External port clients will use to access the service
      targetPort: 8082 # Port on the pods where traffic will be forwarded
  type: LoadBalancer
