apiVersion: v1
kind: Service
metadata:
  name: web-app-bff-service
spec:
  selector:
    app: web-app-bff-deployment
  ports:
    - protocol: TCP
      port: 80 # External port clients will use to access the service
      targetPort: 8081 # Port on the pods where traffic will be forwarded
  type: LoadBalancer
